{
 "title": "Infra azure",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Raw load Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "StorageBlobLogs\r\n| where AccountName == \"devprojetoarmazen\"\r\n| where OperationName == \"PutBlob\"\r\n| extend PathParts = split(ObjectKey, \"/\")\r\n| extend Container = tostring(PathParts[2])\r\n| extend Pasta = tostring(PathParts[4]) \r\n| extend PathParts2 = split(Pasta, \"-\")\r\n| extend local = tostring( tostring(PathParts2[0]) ) \r\n| where Container == \"raw\" // <-- filtro para múltiplos locais\r\n| summarize ArquivosInseridos = count() by Container,bin(TimeGenerated, 1m)\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/97eb265c-59ce-4122-bbe4-98f0d58d9208/resourceGroups/rg-dev-projeto/providers/Microsoft.OperationalInsights/workspaces/law-rg-dev-projeto-dev"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Quantidade Blob Local",
   "type": "table",
   "description": "Quantidade de arquivos que chegaram no blob",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "StorageBlobLogs\r\n| where AccountName == \"devprojetoarmazen\"\r\n| where OperationName == \"PutBlob\"\r\n| extend PathParts = split(ObjectKey, \"/\")\r\n| extend Container = tostring(PathParts[2])\r\n| extend Pasta = tostring(PathParts[4]) \r\n| extend PathParts2 = split(Pasta, \"-\")\r\n| extend local = tostring( tostring(PathParts2[0]) ) \r\n| where local in (\"clientes\", \"items\", \"restaurantes\", \"drivers\", \"orders\" ) \r\n| summarize ArquivosInseridos = count() by Container,local\r\n| order by ArquivosInseridos desc\r\n\r\n\r\n",
      "resources": [
       "/subscriptions/97eb265c-59ce-4122-bbe4-98f0d58d9208/resourceGroups/rg-dev-projeto/providers/Microsoft.OperationalInsights/workspaces/law-rg-dev-projeto-dev"
      ],
      "resultFormat": "table"
     }
    }
   ]
  },
  {
   "title": "source load Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "StorageBlobLogs\r\n| where AccountName == \"devprojetoarmazen\"\r\n| where OperationName == \"PutBlob\"\r\n| extend PathParts = split(ObjectKey, \"/\")\r\n| extend Container = tostring(PathParts[2])\r\n| extend Pasta = tostring(PathParts[4]) \r\n| extend PathParts2 = split(Pasta, \"-\")\r\n| extend local = tostring( tostring(PathParts2[0]) ) \r\n| where Container == \"source\" // <-- filtro para múltiplos locais\r\n| summarize ArquivosInseridos = count() by Container,bin(TimeGenerated, 1h)",
      "resources": [
       "/subscriptions/97eb265c-59ce-4122-bbe4-98f0d58d9208/resourceGroups/rg-dev-projeto/providers/Microsoft.OperationalInsights/workspaces/law-rg-dev-projeto-dev"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Total BlobStorage",
   "type": "gauge",
   "description": "Quantidade de arquivos que chegaram no blob",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "StorageBlobLogs\r\n| where AccountName == \"devprojetoarmazen\"\r\n| where OperationName == \"PutBlob\"\r\n| summarize ArquivosInseridos = count() \r\n| order by ArquivosInseridos desc\r\n\r\n\r\n",
      "resources": [
       "/subscriptions/97eb265c-59ce-4122-bbe4-98f0d58d9208/resourceGroups/rg-dev-projeto/providers/Microsoft.OperationalInsights/workspaces/law-rg-dev-projeto-dev"
      ],
      "resultFormat": "table"
     }
    }
   ]
  },
  {
   "title": "rejeitados load Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "StorageBlobLogs\r\n| where AccountName == \"devprojetoarmazen\"\r\n| where OperationName == \"PutBlob\"\r\n| extend PathParts = split(ObjectKey, \"/\")\r\n| extend Container = tostring(PathParts[2])\r\n| extend Pasta = tostring(PathParts[4]) \r\n| extend PathParts2 = split(Pasta, \"-\")\r\n| extend local = tostring( tostring(PathParts2[0]) ) \r\n| where Container == \"rejeitados\" // <-- filtro para múltiplos locais\r\n| summarize ArquivosInseridos = count() by Container,bin(TimeGenerated, 1h)",
      "resources": [
       "/subscriptions/97eb265c-59ce-4122-bbe4-98f0d58d9208/resourceGroups/rg-dev-projeto/providers/Microsoft.OperationalInsights/workspaces/law-rg-dev-projeto-dev"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  }
 ]
}