name: Deploy Event Grid

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'terraform/modules/eventgrid/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform -chdir=terraform init -backend-config="key=eventgrid.tfstate"

      - name: Terraform Plan (Event Grid)
        run: terraform -chdir=terraform plan -target=module.eventgrid -out=tfplan

      - name: Terraform Apply (Event Grid)
        run: terraform -chdir=terraform apply -auto-approve tfplan
