name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    name: Terraform Dev
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checar repositório
        uses: actions/checkout@v3

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Autenticar no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

      - name: Terraform Init
        working-directory: infra
        run: terraform init -backend-config="storage_account_name=***" -backend-config="container_name=tfstate" -backend-config="key=terraform.tfstate" -backend-config="resource_group_name=rg-backend-dev" -reconfigure
      - name: Executar Terraform Plan
        working-directory: infra
        run: terraform plan -var-file=dev.tfvars

      - name: Executar Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve -var-file=dev.tfvars
