name: Deploy Dev Infra

on:
  push:
    branches:
      - dev

jobs:
  terraform_infra:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform -chdir=infra init

      - name: Terraform Apply Infra + Functions
        run: terraform -chdir=infra apply -auto-approve -var-file=dev.tfvars \
             -target=azurerm_resource_group.grupo_principal \
             -target=azurerm_storage_account.conta_armazenamento \
             -target=azurerm_storage_container.container_raw \
             -target=azurerm_storage_container.container_validado \
             -target=azurerm_storage_container.container_rejeitados \
             -target=azurerm_service_plan.function_plan \
             -target=azurerm_linux_function_app.function_app \
             -target=azurerm_linux_function_app.function_validate
