name: Deploy Infra + Functions

on:
  push:
    branches:
      - dev
    paths:
      - 'terraform/**'
      - '!terraform/modules/eventgrid/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform -chdir=terraform init -backend-config="key=infra-functions.tfstate"

      - name: Terraform Plan (Infra + Functions)
        run: terraform -chdir=terraform plan -target=module.infra -target=module.functions -out=tfplan

      - name: Terraform Apply (Infra + Functions)
        run: terraform -chdir=terraform apply -auto-approve tfplan
