name: Test Azure Secret

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Azure Credentials
        run: |
          echo "Criando arquivo de credenciais do Azure"
          echo '${{ secrets.AZURE_CREDENTIALS_DEV }}' > secret.json
          echo "Conteúdo do arquivo (somente campos importantes):"
          cat secret.json | jq '{clientId, subscriptionId, tenantId}'

      - name: Login no Azure CLI
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS_DEV }}'

      - name: Teste de comando Azure
        run: |
          echo "Listando grupos de recurso no subscription do dev"
          az group list --output table
