name: Test Azure Secret

on:
  push:
    branches:
      - dev

jobs:
  test-secret:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Verificar segredo AZURE_CREDENTIALS_DEV
        run: |
          echo "Criando arquivo de credenciais do Azure"
          echo '${{ secrets.AZURE_CREDENTIALS_DEV }}' > secret.json
          echo "Conteúdo do arquivo (somente campos importantes):"
          cat secret.json | jq '{clientId, subscriptionId, tenantId}'

